### PR TITLE
iframe all tests to see them at once

### PR DESCRIPTION
**Pull request by rogerta**
I made a simple change to the test server so that loading the home page at localhost:8081/ shows the results of all the tests in iframes.  There are links to open each of the individual test pages if needed.  I find this makes it easier to ensure that all the tests pass after a change.  If you don't find  this interesting, feel free to ignore this pull request :-)

### CODE REVIEW

**Comment by Guichaguri** [comment]
Why not use a mustache template instead of raw html, showing how to use lists?

**Comment by rogerta** [comment]
Great idea ☺️ Let me so that when I get some time.

Thanks,
Roger

**Comment by rogerta** [comment]
Please take another look.  I also added a pattern to the .gitignore file to ignore vim backup files.  Thanks.

**Comment by Guichaguri** [comment]
Looks good. Feel free to merge it.
Also, what's your NPM username? I want to give you access to the package so you can publish by yourself :)

**Comment by rogerta** [comment]
Thanks for lgtm.  Will merge.  I don't have an npm account, so just created one: https://www.npmjs.com/~rogerta

**Comment by Guichaguri** [comment]
Done. Feel free to commit and publish the package whenever you want. You are definitely giving more attention to this project than I am...

**Pull request merged**
